language: ruby
rvm:
- ruby-1.9.3
cache: bundler
before_install:
- bundle exec rake travis_key
- export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
- export TRAVIS_COMMIT_SHA1="$(git log --pretty=format:'%h' -n 1)"
- bundle exec rake travis_git_env
script:
- bundle exec rake build
after_success:
- bundle exec rake travis_git_commit