language: ruby
rvm:
- ruby-2.1.7
before_install:
- openssl aes-256-cbc -K $encrypted_23e7d50fa7c4_key -iv $encrypted_23e7d50fa7c4_iv
  -out .travis/travis_rsa.enc -in .travis/travis_rsa -d
- export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
script:
- bundle exec rake build
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/travis_rsa
- ssh-add .travis/travis_rsa
- git remote add origin git@github.com:PlanetVulcan/PlanetVulcan.github.io.git
- git config user.name "Travis CI - Planet Vulcan Robotics"
- git config user.email "info@planetvulcanrobotics.com"
- bash -c 'git commit -m "Travis Build: $TRAVIS_COMMIT_MSG"'
- git subtree push --prefix compiled_site/ origin master
