# Site settings
title: Planet Vulcan
email: info@planetvulcanrobotics.com
description: > # this means to ignore newlines until "baseurl:"
  The new FTC Robotics Team based in Westport, CT.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.planetvulcanrobotics.com" # the base hostname & protocol for your site
github_username:  PlanetVulcan
facebook_username: PlanetVulcanRobotics

# Build settings
markdown: kramdown
exclude: [README.md, Gemfile, Gemfile.lock, CNAME]
