# Site settings
title: Planet Vulcan Robotics
email: green0photon+PlanetVulcan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The new FTC Robotics Team based in Westport, CT.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://planetvulcan.github.io" # the base hostname & protocol for your site
github_username:  PlanetVulcan

# Build settings
markdown: kramdown
