# Site settings
title: Planet Vulcan
email: info@planetvulcanrobotics.com
description: > # this means to ignore newlines until "baseurl:"
  The new FTC Robotics Team based in Westport, CT.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.planetvulcanrobotics.com" # the base hostname & protocol for your site
github_username:  PlanetVulcan
facebook_username: PlanetVulcanRobotics
twitter_username: PVulcanRobotics
youtube_username: PlanetVulcanRobotics9928
gofundme_username: PlanetVulcanRobot

# Build settings
markdown: kramdown
exclude: [Gemfile, Gemfile.lock, Rakefile, design.txt, bower.json]
source: .
destination: ../compiled_site